//
//  IndividualAttributes.swift
//  SrcDataDictV0.2
//
//  Created by Brian on 23/01/2020.
//  Copyright © 2020 Brian. All rights reserved.
//

import Foundation

/**
 * Long-lived first party token representing an app bound to the SRC Profile. The token is intended to be used instead of cookies for non-browser implementations.<br>
 * The “appInstanceId” is generated by SRC System when AppInstance object is provided in Card Enrolment and Add Consumer Identifiers APIs. When client calls Unbind App Instance the association with the provided “appInstanceId” should be removed.<br>
*/
var appInstanceId: String? = nil

/**
Indicates if the “Identity lookup” (Identity Lookup API) was successful or not
*/
var consumerPresent: Bool = false

/**
 Network-specific output data
 */
var customOutputData: JsonObject = JsonObject()

/**
 Session identifier returned by SRC System following an Identity Lookup service call. Can be used in call to Initiate Identity Validation service
 */
var idLookupSessionId: UUID = UUID()

/**
 Session identifier returned by SRC System following an Initiate Identity Validation service call. Used in subsequent call to Complete Identity Validation service.
 */
var idValidationSessionId: UUID = UUID()

/**
 Type of encrypted payload to be returned in the Checkout API response
 */
var payloadTypeIndicatorCheckout: PayloadTypeIndicator = .FULL

/**
Type of encrypted payload to be returned in the Payload API response
*/
var payloadTypeIndicatorPayload:PayloadTypeIndicator = .FULL
